[package]
name = "magic-crypt"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]

[dependencies]
rust-crypto = "0.2.36"
base64 = "0.9.2"
tiger-digest = "0.1.1"
digest = "0.7.5"
des = "0.1.0"
block-modes = "0.1.0"
crc = "1.8.1"